name: Batch jar docker deploy


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  # aws s3 버킷이름
  S3_BUCKET_NAME: inha-unsolved-bucket


jobs:
  batch-job-build:
    runs-on: ubuntu-22.04
    steps:
      # 체크아웃
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}
      # jdk 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "adopt"
      # 서브 모듈 설정 파일 가져오기
      - name: copy config file
        run: |
          cp -r inhaUnsolved-secrets/config ./
        shell: bash
      # 권한 설정 및 빌드
      - name: Build with Gradle

        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
      # 압축
      - name: Make zip file
        run: zip -r ./deploy.zip .
        shell: bash

      # aws 접근 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 압축된 파일을 옮기기
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://$S3_BUCKET_NAME/deploy.zip