name: problem detail renew job

on:
  schedule:
    - cron: "0 0 0/12 * * "

jobs:
  batch-job-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Make config file
        run: |
          cd ./src/main/resources
          touch ./application.yml
          touch ./application-deployDB.yml
          echo "${{ secrets.PROJECT_CONFIG }}" > ./application.yml
          echo "${{ secrets.DB_CONFIG }}" > ./application-deployDB.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Execute Job
        run: |
          java -jar ./batch/build/libs/*.jar \
          --spring.profiles.active=prod \
          --job.name=newProblemAddJob \
          version = ${{GITHUB_RUN_ID}}
          
