name: New problem add job

on:
  schedule:
    - cron: "0 0 */24 * *"
  workflow_dispatch:


jobs:
  batch-job-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Make config file
        run:
          touch ./application.yml
          touch ./application-deployDB.yml
          echo "${{ secrets.BATCH_CONFIG }}" > ./application.yml
          echo "${{ secrets.DOMAIN_CONFIG }}" > ./application-domain.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Execute renewing tagDetail job
        run: |
          java -jar ./batch/build/libs/*.jar \
          --spring.profiles.active=prod \
          --job.name=tagDetailRenewJobConfig \
          version=${{ github.run_id }}

      - name: Execute Job
        run: |
          java -jar ./batch/build/libs/*.jar \
          --spring.profiles.active=prod \
          --job.name=newProblemAddJob \
          version=${{ github.run_id }}
          
      
