#name: solved problem check
#
#
#on:
#  schedule:
#    - cron: "0 0 */1 * *"
#  workflow_dispatch:
#
#concurrency:
#  group: problem-batch
#
#jobs:
#  batch-job-build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#          token: ${{ secrets.ACTION_TOKEN }}
#
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: "adopt"
#
#      - name: copy config file
#        run: |
#          cp -r inhaUnsolved-secrets/config ./
#
#
#
#        shell: bash
#
#
#      - name: Build with Gradle
#        run: |
#          chmod +x ./gradlew
#          ./gradlew clean build -x test
#
#      - name: Execute renewing tagDetail job
#        run: |
#          java -jar ./batch/build/libs/*.jar \
#          --spring.profiles.active=prod \
#          --job.name=tagDetailRenewJobConfig \
#          version=${{ github.run_id }}
#
#      - name: Execute Job
#        run: |
#          java -jar ./batch/build/libs/*.jar \
#          --spring.profiles.active=prod \
#          --job.name=problemSolveCheckJob \
#          version=${{ github.run_id }}